repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=1000]
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
        files: ^/
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: ^/
        args: []
