name: Automated Testing

# what actions and branches to run workflow on
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]


jobs:
  job1:
    # good default
    runs-on: ubuntu-latest

    steps:
      - name: checkout code from current repo into container
        uses: actions/checkout@v2
        with:
          node-version: 18

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run black formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          jupyter: true
          version: "22.3.0"

      - name: run unittests
        run: python unittests

      - name: upload ci/cd report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: report/
          retention-days: 30

             

#linting
