name: Automated Testing

# what actions and branches to run workflow on
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]


jobs:
  job1:
    # good default
    runs-on: ubuntu-latest

    steps:
      - name: checkout code from current repo into container
        uses: actions/checkout@v2
        with:
          node-version: 18

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run ruff formatter
        uses: chartboost/ruff-action@v1

      - name: run pytest
        run: python -m pytest

      - name: upload ci/cd report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.txt
          retention-days: 30

             

#linting
